### ISSUE TITLE
Add Web support

### ISSUE THREAD

**Issue by levischechter** [alan-sdk/alan.dart#140]
as for the latest version of alan (great project!) there is no support for web platform.
is it on the roadmap or it impossible for some reason?

![image](https://user-images.githubusercontent.com/35228498/211563144-bc06223d-0fd0-4995-b107-88b8db81d69e.png)

**Comment by RiccardoM** [comment]
Unfortunately, some of Alan's dependencies do not have Web support. This is why the entire library does not support the Web platform

**Comment by levischechter** [comment]
is it the grpc package? cause it does has web support.
is there another packages?

**Comment by RiccardoM** [comment]
@levischechter Sorry for the late reply. I honestly have no memory about what package is that. I think there might be something native that is used but I can't remember now. If all the dependencies had web support, Alan would be marked as having it as well since that's something that is done automatically. 

Unfortunately right now I don't have the time to activately investigate, but if you want I will gladly accept any PR that adds the Web support

**Comment by levischechter** [comment]
I'll try spare some time for it.
Thanks for the reply.

בתאריך יום ו׳, 3 בפבר׳ 2023, 16:01, מאת Riccardo ***@***.***

**Comment by jonnyjohnson1** [comment]
It is the grpc package. It fails when passing the credentials into the network info.

```credentials: ChannelCredentials.insecure(),```

**Comment by levischechter** [comment]
I think they have a module called grpc_or_grpcweb did you try work with
that?

בתאריך יום ג׳, 14 במרץ 2023, 20:40, מאת jonny ***@***.***>:

**Comment by RiccardoM** [comment]
@jonnyjohnson1 Thanks for poitning this out! I have created #172 with this replacement. Let me know if it works! 
CC @levischechter

**Comment by jonnyjohnson1** [comment]
@RiccardoM Will get to check it over the weekend.

**Comment by jonnyjohnson1** [comment]
@RiccardoM, @levischechter 

The code doesn't work.

The ClientChannel class needs to be updated to GrpcOrGrpcWebClientChannel on these files, too:
tx_sender.dart
tx_signer.dart
querier.dart

When that's done, a new error appears. It occurs on this line.

Error occurs here:
```
final signer = TxSigner.fromNetworkInfo(networkInfo);
```

I've isolated it to this function:
```
Creates a new [ClientChannel] using the optional given options.
  GrpcOrGrpcWebClientChannel getChannel() {
    return GrpcOrGrpcWebClientChannel.grpc(
      host.replaceFirst(RegExp('http(s)?:\/\/'), ''),
      port: port,
      options: ChannelOptions(credentials: credentials),
    );
  }
```

Then this is the error that appears:
Error: Unsupported operation: not supported by gRPC-web

**Comment by levischechter** [comment]
As I see it, We should use the `GrpcOrGrpcWebClientChannel.toSeparateEndpoints` constructor as cosmos grpc server will not work with gRPC-web without an gRPC proxy (something like Envoy) that will mask all grpc-web calls to the server.

in such deployment the user will need to validate that the node runs Envoy or running Envoy proxy for his own use.

**Comment by RiccardoM** [comment]
@levischechter Thanks for the inputs. Are you able to create a PR to that branch with such changes? Thank would mean a lot :pray:

**Comment by levischechter** [comment]
ofcourse! I'll try my best.

**Comment by levischechter** [comment]
@RiccardoM, @jonnyjohnson1 
I created a PR [#175](https://github.com/alan-sdk/alan.dart/pull/175#issue-1631099973).
Didn't had much time to test so I only run the package tests.

If you guys can test it (both for grpc and grpc-web) it will be great
Note: grpc-web tests should run against grpc-web-server\proxy\Envoy

**Comment by jonnyjohnson1** [comment]
@levischechter @RiccardoM 
That fixed the getChannel() function.

New issue:

I am working from this code:

```
final wallet = Wallet.derive(mnemonic, networkInfo);
var msg = {
    "execute_bid": {"bid_amount": bid_amount}
  };
var jsonEncodedMessage = json.encode(msg);
  var binaryEncodedMessage = utf8.encode(jsonEncodedMessage);

  // Create and sign the transaction
  final contractAddress = {contract_address};
  final executeBid = MsgExecuteContract(
      contract: contractAddress,
      msg: binaryEncodedMessage,
      sender: wallet.bech32Address,
      );

  final signer = TxSigner.fromNetworkInfo(networkInfo); <-- previous non-working step, now fixed
  final fee = Fee()..amount.add(Coin(amount: '100000', denom: 'ujuno'));
  fee.gasLimit = 200000.toInt64();
  final tx = await signer.createAndSign(wallet, [executeBid], fee: fee); <-- current step that does not work

  // Broadcast the transaction
  final txSender = TxSender.fromNetworkInfo(networkInfo);
  final response = await txSender.broadcastTx(tx);
```

Now, in the createAndSign function (tx_signer.dart), the hang up is on the AuthQuerier class.

The line takes a while to run, and eventually returns the error shown below.

```
final account = await _authQuerier.getAccountData(wallet.bech32Address);

// which has this function
Future<AccountI?> getAccountData(String address) async {
    final request = auth.QueryAccountRequest.create()..address = address;
    final response = await _client.account(request); <-- this line takes a while and fails, I return nothing past it
    if (!response.hasAccount()) {
      return null;
    }
```

Returns this error:
Error: gRPC Error (code: 2, codeName: UNKNOWN, message: HTTP request completed without a status (potential CORS issue), details: null, rawResponse: , trailers: {})
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49      throw_
packages/grpc/src/shared/status.dart 385:5                                        validateHttpStatusAndContentType
packages/grpc/src/client/transport/xhr_transport.dart 103:7                       [_validateResponseState]
packages/grpc/src/client/transport/xhr_transport.dart 122:31                      [_onRequestDone]
packages/grpc/src/client/transport/xhr_transport.dart 65:11                       <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 367:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 372:39  dcall
dart-sdk/lib/html/dart2js/html_dart2js.dart 37340:58                              <fn>

**Comment by levisjct** [comment]
Do you run it on app or web?
If on web is it against Envoy?

**Comment by jonnyjohnson1** [comment]
I ran on web and didn't run against Envoy.

I am unsure of that kind of setup, but found this as a demo to work from. I'll have to try it tomorrow: https://stackoverflow.com/questions/59558293/can-grpc-be-integrated-into-flutter-web.

Is the Envoy proxy needed only for testing in debug mode, or is it setup, too, once the app is deployed and hosted somewhere?

**Comment by levischechter** [comment]
Hello guys,
I added a new pull request [#194 ](https://github.com/alan-sdk/alan.dart/pull/194).
I tested it with android and web and it works fine against cosmos-sdk based blockchain.
Please merge it.
