### ISSUE TITLE
Upgrade build runner to latest version.

### ISSUE THREAD

**Issue by kjawadDeveloper** [alan-sdk/alan.dart#71]
The alan project right now breaks projects that use build_runner: 2.2.0.

**Comment by kjawadDeveloper** [comment]
@RiccardoM i solved it in my fork project . Should I create a PR for that?

**Comment by RiccardoM** [comment]
@kjawadDeveloper Yeah that would be great if you could do it

**Comment by kjawadDeveloper** [comment]
@RiccardoM great than.

**Comment by RiccardoM** [comment]
Closed with #72
