### ISSUE TITLE
Provide support for comos sdk 0.46.0-rc3

### ISSUE THREAD

**Issue by kjawadDeveloper** [alan-sdk/alan.dart#73]
when i am using alan library with cosmos SDK 0.46.0-rc3 it fails on alan signing. Apparatently the node info URL and the response structure has been change in the latest version . 

From 
http://URL/node_info

to 
http://URL/cosmos/base/tendermint/v1beta1/node_info

Because of which the transaction signing is failing.

**Comment by kjawadDeveloper** [comment]
@RiccardoM  what you think about this?

**Comment by RiccardoM** [comment]
@kjawadDeveloper Can I get some more details? When was that endpoint introduced? Maybe we can use that since Cosmos v0.45? Or is it something related to v0.46 only?

**Comment by kjawadDeveloper** [comment]
So right now in TxSigner we are using nodeQuerier to get the chainId but the endpoint has been chain and its structure is also changed in the 0.46 of the cosmos SDK.
