### ISSUE TITLE
Add support for feegrants

### ISSUE THREAD

**Issue by arrivets** [alan-sdk/alan.dart#78]
## Feature description 

I would like to be able to set the `fee-account` property on a tx.
This allows for the transaction fees to be paid by another account.

## Implementation proposal

THere is already a `payer` field in your `Fee` class, but it doesn't seem to be used.

I suppose you would have to update the TxBuilder with a `setFeeAccount` method, add call it in TxSigner when constructing the tx:

```
final tx = config.newTxBuilder()
      ..setMsgs(msgs)
      ..setSignatures([sig])
      ..setMemo(memo)
      ..setFeeAmount(fee.amount)
      ..setGasLimit(fee.gasLimit)
     ?????????  ..setFeeAccount(fee.payer). ??????????
```

**Comment by RiccardoM** [comment]
Thanks for the find! This has now been added and it's available inside version `0.41.1+1`
