### ISSUE TITLE
Will this support Cosmwasm / Adding Cosmwasm Support ?

### ISSUE THREAD

**Issue by rakataprime** [alan-sdk/alan.dart#80]
## Feature description 

The cosmwasm smart contract language is used with many cosmos chains including juno and stargaze.  There is a cosmjs cosmwasm signing client for building dapps with cosmwasm support. https://cosmos.github.io/cosmjs/latest/cosmwasm-stargate/index.html.  https://github.com/cosmos/cosmjs The main functionality is adding a cosmwasm signer equivalent to the js client. 

## Implementation proposal
adding a cosmwasm signer module and add cosmwasm cosmos sdk module

**Comment by RiccardoM** [comment]
We have already released CosmWasm support with version [0.41.1+1](https://github.com/alan-sdk/alan.dart/blob/main/CHANGELOG.md#version-04101) which implements #39
