### ISSUE TITLE
Failure to Query/Connect to RPC endpoints 

### ISSUE THREAD

**Issue by rakataprime** [alan-sdk/alan.dart#85]
## Generic information
- Alan.dart version:  ^0.41.1+1
- Application type (web/Flutter): vanilla dart and flutter 
- OS linux 

## Bug description
(this is an awesome project !!) 

Having difficulty connecting to rpc endpoints for cosmos/juno/desmos

I have tried to reproduce the example in the documentation @ https://alan-sdk.github.io/alan.dart/queries/overview.html#common-data

I cannot connect to any rpc endpoints so far after testing https://rpc-juno.itastakers.com, https://rpc-desmos.itastakers.com, and https://rpc.cosmos.smartnodes.one

I do not believe that Juno should require addditional .proto for anything other than the mint module, but I also had a hard time understanding that portion of the documentation.

I did not find any tests so far that demonstrate connectivity to an rpc endpoint.  

I would recommend adding a test or example that demonstrates the queries from the docs. 

Error from script below:

gRPC Error (code: 14, codeName: UNAVAILABLE, message: Error connecting: SocketException: Connection timed out (OS Error: Connection timed out, errno = 110), address = rpc-desmos.itastakers.com, port = 34944, details: null, rawResponse: null, trailers: {})

## Steps to reproduce
created a test.dart script with the following and run with dart run test.dart
```import "package:alan/alan.dart";
import 'package:alan/proto/cosmos/staking/v1beta1/export.dart' as staking;

Future<staking.QueryValidatorsResponse> _validatorQuery(channel) async {
  final stakingClient = staking.QueryClient(channel);
  print("starting query");
  final pagination = PageRequest.create()
    ..limit = 100.toInt64()
    ..offset = 0.toInt64();
// Query the gRPC
  final response = await stakingClient.validators(
    staking.QueryValidatorsRequest.create()..pagination = pagination,
    // ..status = status
  );
  print("done query");
  print(response);
  return response;
}

void main() {
  final networkInfo = NetworkInfo.fromSingleHost(
    // bech32Hrp: "juno",
    // host: "https://rpc-juno.itastakers.com",
    // bech32Hrp: "cosmos",
    // host: "https://rpc.cosmos.smartnodes.one",
    // bech32Hrp: "desmos",
    // host: "https://rpc-desmos.itastakers.com",
    bech32Hrp: "desmos",
    host: "localhost",
  );
  final channel = networkInfo.gRPCChannel;
  final resp = _validatorQuery(channel).then((resp) {
    print(resp);
  });
  print(resp);
}
```

**Comment by RiccardoM** [comment]
Your code seems correct. It's very likely that the endpoints you have tried using (`https://rpc-juno.itastakers.com`, `https://rpc-desmos.itastakers.com`, and `https://rpc.cosmos.smartnodes.one`) simply *do not* expose the gRPC server. 

I would try asking the maintainer of those nodes if they can provide you with a gRPC server URL, and then using the following code to create a proper `NetwotkInfo` instance.

Example:
```dart
final networkInfo = NetworkInfo(
    bech32Hrp: 'desmos',
    lcdInfo: LCDInfo(host: 'https://lcd.morpheus.desmos.network', port: 443),
    grpcInfo: GRPCInfo(
      host: 'https://grpc.morpheus.desmos.network',
      port: 443,
      credentials: ChannelCredentials.secure(),
    ),
  );

**Comment by RiccardoM** [comment]
Closing this due to no answer from original poster
